# Generated by Django 5.0.6 on 2025-02-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0002_question_choice_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice",
            new_name="question",
        ),
    ]
